### ISSUE TITLE
Error when using simulated reads from ecSimulator

### ISSUE THREAD

**Issue by uretaj** [jluebeck/CycleViz#18]
Hi,

I'm getting this error whenever I try to use simulated reads from ecSimulator

`$ /CycleViz/CycleViz.py --ref GRCh38 --cycles_file test_amplicon1_BPG_converted_cycles.txt --cycle 1 -g est_amplicon1_graph.txt  --rotate_to_min --figure_size_style small`

`CycleViz 0.1.10
Using resources in CycleViz/resources/
Plots will use reference hg38
Using figure_size_style=small
Bar width scaled up 1.5x to 1.05
Gene fontsize scaled up 2x to 14
Tick fontsize scaled up 1.5x to: 6.0
checking adjacency
plotting structure
Reading genes
plotting genes
Traceback (most recent call last):
  File "/CycleViz/CycleViz.py", line 1418, in <module>
    plot_bpg_connection(ref_placements, total_length, prev_seg_index_is_adj, bpg_dict, seg_end_pos_d)
  File "/CycleViz/CycleViz.py", line 106, in plot_bpg_connection
    bpg_dict, seg_end_pos_d)
  File "/CycleViz/VizUtil.py", line 294, in pair_is_edge
    rObj1_end = seg_end_pos_d[a_id][-1] if a_dir == "+" else seg_end_pos_d[a_id][0]
KeyError: '14'
`

**Comment by jluebeck** [comment]
Hi, 

Thanks for sending this error. The cause is likely because you shouldn't use the BPG-converted version of the cycles file when using input from ecSimulator, simply use the simulated graph and cycles files as given in that case. 

I plan to simplify this process in the future to avoid confusion. 

Thanks and sorry for the confusion! 
Jens
